version: '3'

services:
  app:
    container_name: tech_java_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/local/tomcat/webapps
